✨ Added self-updater

diff --git a/bob b/bob
--- a/bob
+++ b/bob
@@ -6,6 +6,7 @@
 # Provide easy access to Bob CLI
 
 # Define colors for fancy output
+RED="\033[31m"
 GREEN="\033[32m"
 YELLOW="\033[33m"
 MAGENTA="\033[35m"
@@ -62,18 +63,52 @@ done
 
 # Check if PHP executable was found
 if [ -z "$PHP_PATH" ]; then
-    echo -e "❌ I have a bad feeling about this... PHP not found."
-    echo -e "  Ensure PHP is installed and the path is set correctly."
+    echo -e "❌ ${RED}I have a bad feeling about this... PHP not found."
+    echo -e "  Ensure PHP is installed and the path is set correctly.${RESET}"
     exit 1
 fi
 
 # Check if Composer is installed
 if ! command -v composer &> /dev/null
 then
-    echo -e "❌ It's a trap! Composer not found."
+    echo -e "❌ ${RED}It's a trap! Composer not found."
     echo -e "  Install Composer and ensure it's available"
-    echo -e "  in your PATH to continue your journey."
+    echo -e "  in your PATH to continue your journey.${RESET}"
     exit 1
+fi
+
+# Self-updater
+if [ "$1" == "self-update" ]; then
+    # Bob CLI: Self-Update
+    # ---------------------
+    # Initiating hyperdrive sequence...
+    # Fetching latest updates from the galaxy far, far away...
+
+    echo -e "${CYAN}Commencing self-update...${RESET}"
+
+    # Fetch the latest version of the Bob script from GitHub
+    curl -fSsL -o /tmp/bob https://raw.githubusercontent.com/neoground/charm-toolkit/main/bob
+
+    # Check if the downloaded script is valid and has the necessary permissions
+    if [ -s /tmp/bob ] && chmod +x /tmp/bob; then
+      # Replace the existing Bob script with the latest version
+      echo -e "Moving new version to /usr/local/bin/bob..."
+      if [[ $(id -u) -ne 0 && -x $(command -v sudo) ]]; then
+          sudo mv /tmp/bob /usr/local/bin/bob
+      elif [[ $(id -u) -eq 0 ]]; then
+          mv /tmp/bob /usr/local/bin/bob
+      else
+          echo -e "${RED}Failed moving bob to /usr/local/bin/bob! The Force is not strong with this update...${RESET}"
+          echo "Please run with sudo or as root."
+          exit 1
+      fi
+      mv /tmp/bob /usr/local/bin/bob
+
+      echo -e "${GREEN}✅ Update successful! Bob is now ready!${RESET}"
+    else
+      # In case the download failed or the script is not executable
+      echo -e "${RED}Update failed! The Force is not strong with this update...${RESET}"
+    fi
 fi
 
 # Create new project
@@ -101,6 +136,12 @@ if [ "$1" == "new" ]; then
     echo -e "${CYAN}Creating new project: $2 ${RESET}"
     echo " "
 
+    # Check if dir exists
+    if [ -d "$2" ]; then
+        echo -e "${RED}Project directory already existing!${RESET}"
+        exit 1
+    fi
+
     # Create new project directory
     mkdir "$2"
 
@@ -116,6 +157,10 @@ if [ "$1" == "new" ]; then
     echo -ne "[..] Creating directory structure...\r"
     mkdir -p var/cache var/logs data app/Config/Environments
     chmod -R 0777 var/cache var/logs data
+
+    # Remove charm-wireframe git stuff
+    rm -Rf .git
+
     echo -ne "${GREEN}[OK]${RESET} Created directory structure     \n"
 
     # Install dependencies using Composer
@@ -188,7 +233,7 @@ outputRainbow "██      ███████ ███████ ███
 outputRainbow "██      ██   ██ ██   ██ ██   ██ ██  ██  ██"
 outputRainbow " ██████ ██   ██ ██   ██ ██   ██ ██      ██"
 echo " "
-echo -e "${MAGENTA}Welcome to Bob, the Intergalactic Charm Framework Toolkit!${RESET}"
+echo -e "${CYAN}Welcome to Bob, the Intergalactic Charm Framework Toolkit!${RESET}"
 echo ""
 echo -e "In a galaxy far, far away, Bob is your trusty droid companion,"
 echo -e "here to assist you with your Charm Framework projects."
